// Initial vocabulary captured from BambooHR on 2026-09-09. New observed titles remain reviewable.
export const BAMBOO_JOB_TITLES = [
  "Account Payable Specialist",
  "Accountant",
  "Accounting Manager",
  "Administrative Intern",
  "Area Manager",
  "Area Superintendent",
  "Assistant Carpenter",
  "Assistant Controller",
  "Assistant Equipment Manager",
  "Assistant Mechanic",
  "Assistant Project Manager",
  "Assistant Superintendent",
  "Blade Finisher",
  "CAD Technician",
  "Carpenter",
  "Carpenter Helper",
  "Carpenter II",
  "Chief Civil Estimator",
  "Chief Executive Officer",
  "Chief Financial and Administrative Officer",
  "Chief Financial Officer",
  "Chief Revenue Officer",
  "Chief Surveyor",
  "Concrete Finisher",
  "Concrete Finisher II",
  "Controller",
  "COO Urban Nepal",
  "Crane Operator",
  "Curb Man",
  "Data Entry Specialist",
  "Diesel Mechanic",
  "Diesel Mechanic III",
  "Director of Civil Operations",
  "Director of Estimating- Water Department",
  "Director of Project Controls",
  "Dispatcher",
  "Driver",
  "Earthworks Foreman",
  "Engineering Technician",
  "Equipment Detailer",
  "Equipment Manager",
  "Equipment Operator",
  "Estimating Coordinator",
  "Estimating Engineer",
  "Estimating Technician",
  "Estimator",
  "Executive Assistant",
  "Executive Vice President of Human Resources",
  "Field Engineer",
  "Field Engineer 1",
  "Field Engineer 2",
  "Field Engineer 3",
  "Field Engineer Intern",
  "Foreman",
  "Foreman - Dirt",
  "Foreman - Flatworks",
  "Foreman - Structures",
  "Foreman - Traffic",
  "Form Setter",
  "FP&A Manager",
  "General Superintendent",
  "Heavy Crane Technician",
  "Heavy Haul Driver",
  "HR Administrator",
  "HR Assistant",
  "HR Coordinator",
  "HR/Payroll Analyst",
  "Human Resources Manager",
  "Internal Controls & Systems Manager",
  "Jr. Human Resources Generalist",
  "Labor",
  "Leadman",
  "Mantis IT",
  "Marketing Manager",
  "Mechanic",
  "Office Administrator",
  "Office and Safety Coordinator",
  "Office Manager",
  "Operator",
  "Operator - Crane",
  "Operator - Excavator",
  "Operator - Loader",
  "Operator - Misc",
  "Operator- Dozer",
  "Paving Equipment Foreman",
  "Paving Finisher",
  "Paving Foreman",
  "Paving Machine Mechanic",
  "Paving Machine Operator",
  "Payroll",
  "Payroll Specialist",
  "Payroll Supervisor",
  "Pipe Foreman",
  "Pipe Layer",
  "Pipe Man",
  "Pipe Man Helper",
  "Pre-Construction Coordinator",
  "Procurement Manager",
  "Procurement Specialist",
  "Project Administrator",
  "Project Director",
  "Project Engineer",
  "Project Manager",
  "Quality Control Manager",
  "Safety Manager",
  "Safety Program Administrator",
  "Safety Specialist",
  "Saw Operator",
  "Senior Accountant",
  "Senior Estimator",
  "Senior Project Engineer",
  "Senior Project Manager",
  "Senior Superintendent",
  "Sr. Vice President of Finance",
  "Staff Accountant",
  "Staff Accountant Intern",
  "Straight Edgeman",
  "Superintendent",
  "Survey Helper",
  "Survey Manager",
  "Survey Party Chief",
  "Talent Acquisition Manager",
  "Talent Acquisition Specialist",
  "Telehandler Operator",
  "Traffic Control Helper",
  "Utilities Foreman",
  "Utilities Superintendent",
  "Utility Labor",
  "Vice President of Finance",
  "VP of Estimating",
  "Welder"
] as const;
